- .github/README.md
💁 These changes update the README to improve the documentation for new readers. I've made an effort to remove duplication and make it easier for "zero knowledge" readers.
* NPM -> npm
* Remove "we" from documentation
* Add descriptions for each bare command
* miscellaneous other edits and tweaks
> Miscellaneous docs edits

- src/index.ts
Exporting paymentIntents class missed on #276 .
> fix(payment-intents): export paymentIntents class

- package.json
- rollup.config.js
We previously were bundling devDependencies instead of the dependencies and this was causing issues when bundling our SDK.
This seems to cause the issue reported (#418)
> fix(bundle): bundle dependencies correctly

- examples/with-next/README.md
💁 To make the intent clearer to me after reading the documentation for the `create-next-app` example, I've made some small edits to reflect what this example app does.
> fix: update Next.js application example docs

- .github/renovate.json
I think these are safe to be auto merged as they can't break anything. Note, this is part of my effort to slowly ratchet up the number of packages we auto merge.
> [No Jira] Add commitlint packages to list of automerged ones

- .github/renovate.json
This is safe to auto merge as it can't break anything.
> [No Jira] Add lint-staged to automerge

- src/Places/Suggestions/Suggestions.ts
- src/Places/Suggestions/SuggestionsType.ts
- src/Places/Suggestions/mockSuggestions.ts
Updating the type name to match our code structure/standards. This was missed in the previous pull request.
> fix(places): update type name to match code standards

- src/DuffelPayments/Refunds/Refunds.spec.ts
- src/DuffelPayments/Refunds/Refunds.ts
- src/DuffelPayments/Refunds/RefundsType.ts
- src/DuffelPayments/Refunds/index.ts
- src/DuffelPayments/Refunds/mockRefunds.ts
- src/index.ts
Adds support for [refunds](https://duffel.com/docs/api/refunds)
> feat(duffel-payments): add ability to request and create refunds

- src/Client.ts
We've done a soft release of v1 and will begin using it as there's no material differences to the beta version.
> Switch version to v1

- src/booking/Orders/OrdersTypes.ts
- src/booking/Orders/mockOrders.ts
This PR fixes the `AddServices` interface.
> fix(booking): fix payment interface

- src/booking/Orders/Orders.ts
This PR fixes the request options for adding services to existing orders.
> fix(booking): fix request options for adding services

- src/booking/OfferRequests/OfferRequestsTypes.ts
Recreating https://github.com/duffelhq/duffel-api-javascript/pull/653 but not as a fork, with a semantic commit message.
> fix(types): use correct type for passenger type

- src/booking/AirlineInitiatedChanges/index.ts
- src/booking/index.ts
- src/index.ts
We added the methods but we forgot to exposed them 😓
> feat(aic): expose Airline-initiated changes API

- src/Stays/Bookings/Bookings.spec.ts
- src/Stays/Bookings/Bookings.ts
This PR adds a `cancel` function to `stays.booking`
> [STAYS-521] Add cancel booking to Stays

- package.json
- yarn.lock
https://github.com/duffelhq/duffel-api-javascript/security/dependabot/14
https://github.com/duffelhq/duffel-api-javascript/security/dependabot/15
> build: fix semver & word-wrap vulnerabilities

- src/Stays/StaysTypes.ts
- src/Stays/mocks.ts
Adds a couple missing properties to Stays bookings.
> fix: add rooms to bookings

- src/Stays/mocks.ts
> fix: small change to trigger release

- src/Places/Suggestions/Suggestions.ts
As per https://github.com/duffelhq/duffel-api-javascript/issues/782
Aligning with docs: https://duffel.com/docs/api/v1/places/get-place-suggestions
> fix: place suggestions types

- package.json
Manual bump as I accidentally published 2.5.7 in the mean time :)
> ci(release): 2.5.8

- package.json
to resolve [this thread](https://duffel.slack.com/archives/C013XQ3T2J1/p1698245595904039)
> fix: bumps version for manual release

- src/types/shared.ts
To address https://github.com/duffelhq/duffel-api-javascript/issues/833
> fix: make penalty currency nullable

- .github/ISSUE_TEMPLATE /bug_report.md
Should make it easier for folks reporting issues to know what to include so we have enough information to help.
> Creates bug_report.md template

- src/Stays/StaysTypes.ts
- src/Stays/mocks.ts
__what__
Adds missing card_component_key attribute to quote type
> card_component_key attribute

- src/Stays/StaysTypes.ts
- src/Stays/mocks.ts
Adds the following new attributes:
- rating and review score to accommodation
- number of adult guests and rooms to search result and quote
> Add new stays attributes

- src/Stays/StaysTypes.ts
To match https://github.com/duffelhq/platform/pull/16961/files
> fix: amend board types and rating sources

- src/Stays/StaysTypes.ts
- src/Stays/mocks.ts
This prepares for our upcoming key collection instructions update on bookings.
> Adds StaysBooking key collection instructions

- src/booking/Offers/OfferTypes.ts
- src/booking/Offers/mockOffer.ts
- src/booking/Offers/mockPartialOffer.ts
- src/booking/Orders/mockOrders.ts
- src/types/shared.ts
This adds new NGS (and some other missing) types based on https://github.com/duffelhq/platform/pull/17358/files.
⚠️ do not merge until the backend work is merged (and I will check if any updates are needed if that changes)
Once this is in I'll update the component.
> feat: add new NGS related types

- package.json
__what__
Replicates @timrogers' https://github.com/duffelhq/duffel-api-javascript/pull/934, which got stuck on CI
> chore: update package.json metadata to improve Dependabot PRs for this package

- package.json
- src/Client.ts
- src/Stays/Accommodation/Accommodation.spec.ts
- src/Stays/Accommodation/Accommodation.ts
- src/Stays/StaysTypes.ts
This creates an interface to communicate with the new duffel endpoint for listing accommodation
https://duffel.com/docs/api/v2/accommodation/list-accommodation
> feat: create SDK interface for accommodation listing

- src/Stays/Stays.ts
- src/Stays/StaysTypes.ts
Fixes https://github.com/duffelhq/duffel-api-javascript/issues/1000
> feat: correct typing for stays search response

- src/booking/SeatMaps/SeatMapTypes.ts
Adds missing exclude for the seat element types.
> fix: adds missing exclude

- src/index.ts
Exporting directly from the index doesn't work, we need to import and then export from a different `const`
> Exports new functions

- src/Identity/CustomerUsers.ts
- src/Identity/Identity.spec.ts
to facilitate calls to the [GET /idenity/customer/users endpoint](https://github.com/duffelhq/platform/pull/22211).
> Adds list endpoint for customer users

- src/Stays/Stays.spec.ts
- src/Stays/StaysTypes.ts
Adds these new parameters to the request.
> feat: add mobile and free cancellation only to stays search request [STAY-2847]

- src/booking/Identity/ComponentClientKey/index.ts
- src/booking/Identity/index.ts
- src/booking/OrderChanges/OrderChanges.ts
- src/booking/index.ts
Fixes for:
- https://github.com/duffelhq/duffel-api-javascript/issues/998
- https://github.com/duffelhq/duffel-api-javascript/issues/982
> Address a couple reported issues

- src/functions/hasAvailableSeatService.spec.ts
- src/functions/hasAvailableSeatService.ts
- src/functions/hasService.spec.ts
- src/functions/hasService.ts
To fix errors when integrating
> fix: type import
