package.json, yarn.lock
We were already using TS 4.4.2, but the package.json didn't reflect it
=> build(deps-dev): bump typescript and rollup-plugin-dts

src/booking/Offers/OfferTypes.ts, src/booking/Offers/Offers.spec.ts, src/booking/Offers/mockOffer.ts, src/booking/Orders/Orders.spec.ts, src/booking/Orders/OrdersTypes.ts, src/booking/Orders/mockOrders.ts
- add `family_name`, `given_name`, and `loyalty_programme_accounts` fields to OfferPassenger interface
- add `loyalty_programme_accounts` field to the OrderPassenger interface
- add unit tests
=> feat(booking): add new fields to Order and Offer passenger data

jest.config.js, package.json, yarn.lock
What says in the tin. Also, this will fix the security issue highlighted by Dependabot.
=> build(deps-dev): bump jest to latest version

src/booking/OfferRequests/OfferRequests.ts, src/types/ClientType.ts
The field is validated in the backend so we would rather surface validation errors from there directly if the field is invalid.
=> fix(booking): remove passenger validation from OrderRequests.create

src/DuffelPayments/PaymentIntents/PaymentIntents.spec.ts, src/DuffelPayments/PaymentIntents/PaymentIntents.ts
We defined the wrong path inside PaymentIntents. This fixes the issue reported on #324.
=> fix(payments): point payment intents to the correct path

commitlint.config.js
Some of dependabot's PR messages are longer than the [default maximum character length of `72`](https://github.com/conventional-changelog/commitlint/tree/master/@commitlint/config-angular) leading to the following error during CI:
```
✖   header must not be longer than 72 characters, current length is 78 [header-max-length]
```
This PR increases the `header-max-length` commitlint rule to `80` to allow these PRs to pass the CI check.
=> ci: increase commitlint header-max-length rule to 80

.eslintrc.js
When linting, GitHub actions marks "Danvers" as a misspelled word:
```
You have a misspelled word: Danvers on String
```
"Danvers" is used as a mock passenger's family name when creating a mock order and is the correct spelling. This PR adds "Danvers" to list of words to skip during the spellcheck to git rid of this warning.
=> build: add "Danvers" to eslint skipWords

src/booking/Orders/OrdersTypes.ts
At the moment, the Typescript types in the library force you to provide a list of `payments` when creating an order.
`payments` is required for so-called "instant" orders.
But we should not validate this in the `CreateOrder` type because when creating a hold order (`type: "hold"`), `payments` are not required (and in fact cannot be provided!).
If you try to not pass `payments` when creating an `instant` order, the types will now allow it but you will get an error back from the API.
This bug was reported by an integrator, who is currently blocked by it, so it would be wonderful to get it merged!
=> fix(orders): don't require `payments` when creating an order

src/booking/OfferRequests/OfferRequests.ts, src/booking/OfferRequests/OfferRequestsTypes.ts
Previously, the `create` method's parameter type allows every parameter to be optional when in reality the endpoint requires `slices` and `passengers` to always be passed along. This fixes that.
=> fix(offer requests): tighten OfferRequests types

src/booking/OfferRequests/OfferRequests.spec.ts, src/booking/OfferRequests/OfferRequests.ts, src/booking/OfferRequests/OfferRequestsTypes.ts
When an offer request is created with `return_offers` being false, the API won't return any offers. So we will reflect that in the type as well.
Demo:
=> fix(offer requests): ensure `offers` is inaccessible when `return_offers=false`

src/booking/OfferRequests/OfferRequests.ts, src/booking/Offers/Offers.ts
Previously we referred to Client without using its relative path. This causes the build to fail (example: https://github.com/duffelhq/duffel-api-javascript/issues/372). This commit fixes it by refer to `Client` using a relative path instead
=> fix(offers): import `Client` using a relative path

src/booking/OfferRequests/OfferRequests.ts, src/booking/Offers/Offers.ts
Importing `Client` caused `node-fetch` to be included in the package, and our rollup configuration doesn't support the way that package export things right now.
=> fix(offers, offer requests): remove `Client` import

jest.config.ts, package.json, rollup.config.js, src/Client.ts, src/booking/OfferRequests/OfferRequests.spec.ts, yarn.lock
Since the security PR merged (https://github.com/duffelhq/duffel-api-javascript/pull/371) rollup couldn't build a new release. We now removed the dependency from isomorphic-unfetch, since we don't support client-side calls, and replaced it with `node-fetch` which was a dependency from the previous package.
A few other updates from the PR:
- Moved `plugins` from semantic-release inside `release` to fully support it features;
- Updated jest.config.ts to support ES6 properly;
- Bumped other plugins;
=> fix: remove isomorphic-unfetch and use node-fetch instead

src/booking/OrderCancellations/OrderCancellations.spec.ts, src/booking/OrderCancellations/OrderCancellations.ts, src/booking/OrderCancellations/OrderCancellationsTypes.ts, src/booking/OrderCancellations/mockOrderCancellations.ts
The Order Cancellations API [supports][1] listing order cancellations - optionally filtered by order ID.
This makes that functionality available in the library, with both manual pagination (`list`) and auto-pagination (`listWithGenerator`).
This gap in the library was reported by an integrator via a support ticket.
[1]: https://duffel.com/docs/api/order-cancellations/get-order-cancellations
=> feat(order-cancellations): add support for listing Order Cancellations

package.json, yarn.lock
The latest version from node-fetch dropped support for CommonJS and not all the users migrated to an ES Module only world. This pull request rollback node-fetch to 2.x.x latest version which still supports commonjs.
This fixes #418
=> fix(client): rollback node-fetch to 2.x.x

src/Client.ts
This is to allow us to have more visibility on where the API is being made from, so we can prioritize our further investment. The source will become part of the userAgent and would allow us to perform analytics on the usage. 
Apps created via `create-duffel-app` will have source populated to include the information of the type of templates being use.
=> feat(client): add `source` to client config (UXP-2045)

src/booking/Orders/OrdersTypes.ts, src/booking/Orders/mockOrders.ts
Update the types for order creation passengers to match the schema https://duffel.com/docs/api/orders/create-order
- passenger's `type` is deprecated 
- `identity_documents` is optional
=> fix(order): fix the expected type for order creation passengers

src/index.ts
This is so that the client code can handle Duffel-specific error more nicely using `e instanceof DuffelError`
=> fix(client): export DuffelError

src/Client.ts, src/index.ts, src/types/ClientType.ts
Previously DuffelError was exported as both a type and a value. This led to a naming conflict and caused `DuffelError` to not be importable through `@duffel/api`.
To fix that, we will move this class out of `ClientType`, so that it can be imported as both a value and a type.
=> fix(client): fix DuffelError exporting

package.json
The `commitzen` package has not been [updated since 7 May 2021](https://github.com/commitizen/cz-cli/tree/v4.2.4) which means that numerous security patches haven't been released as new package versions.
This change forces a version on `minimist` which is not vulnerable to CVE-2021-44906.
See this following security advisory for more information:
https://github.com/advisories/GHSA-xvch-5gv4-984h
=> Force `minimist` to resolve to v1.2.6

src/Client.ts, src/booking/Offers/OfferTypes.ts, src/booking/Offers/mockPartialOffer.ts, src/booking/PartialOfferRequests/PartialOfferRequestTypes.ts, src/booking/PartialOfferRequests/PartialOfferRequests.spec.ts, src/booking/PartialOfferRequests/PartialOfferRequests.ts, src/booking/PartialOfferRequests/index.ts, src/booking/PartialOfferRequests/mockPartialOfferRequest.ts
Adds support for [partial offer requests](https://duffel.com/docs/api/partial-offer-requests) which in used multi-step search
flow.
Required changing the client to handle array query string parameters by
repeating array key.
=> feat(booking): add Partial Offer Requests api

.github/workflows/main.yml
__what__
When developers are raising PRs from forked branches our Github checks are not running. Seif had this issue before and Tim just had this issue. This updates our main action to Github Actions from push to pull_request_target to allow that.
=> build(gh-actions): uses on pull_request_target hook

.github/workflows/main.yml
See [this Slack thread](https://duffel.slack.com/archives/C033WEHE4CR/p1655136888645379?thread_ts=1655113215.075649&cid=C033WEHE4CR) for more context
=> build(gh-actions): prevent ci running on pull_request_target

.github/renovate.json
This should prevent the issues we're seeing on Renovate's other PRs where it's using `chore` which isn't allowed under our commit conventions.
=> build: make renovate use build for commit messages

.github/renovate.json, CONTRIBUTING.md
This is the final Renovate PR from me as part of this ticket. Now that we've had Renovate running all week without issue, it adds some configuration options aimed at reducing the workload from managing dependency updates.
It does the following:
* Only runs Renovate weekly, prior to work on Monday. This will mean we only have to worry about dependency updates once per week.
* Combines patch and minor updates into a single PR, to make it easier to manage. The PR may be slightly more work to review, but the benefits should outweigh the downsides as the overhead from merging one larger PR is much smaller than merging several small PRs.
* Turns on automerge for eslint and Prettier. I have deliberately been very conservative with which dependencies can automerge, as it's potentially dangerous. …
=> [UXP-2482] Make Renovate config more opinionated

package.json, yarn.lock
node-fetch v3.0 is ESM-only, and upgrading to that means that our library would be unusable for the users who can't afford to migrate to ESM yet. So we will stick with 2.6.7 for the time being. The maintainers promised that bugs will still continue to be handled in the v2 version so we will take their words for it for now.
=> fix(build): downgrade node-fetch to 2.6.7

src/Client.ts, src/types/ClientType.ts
__what__
Before, we'd only return the http body, this meant users don't have visibility on rate limiting and request id headers. This PR includes the headers object on every success and error response.
=> feat(headers): shows http headers in client response

src/types/ClientType.ts
This PR updates the `headers` type in the `DuffelResponse` interface to match what is returned from `fetch`.
The current headers type (`Record<string, string>`) was causing issues when trying to apply headers to a server response on our internal dashboard tool.
=> fix(headers): update response interface to use correct headers type

src/booking/Orders/Orders.spec.ts, src/booking/Orders/Orders.ts, src/booking/Orders/OrdersTypes.ts, src/booking/Orders/mockOrders.ts
This PR adds functionality for getting available services for an order, and booking services for an order.
Docs:
- https://duffel.com/docs/api/orders/create-order-services
- https://duffel.com/docs/guides/adding-post-booking-bags
=> feat(booking): add ability to retrieve and add services for an order

src/booking/OfferRequests/OfferRequestsTypes.ts, src/booking/OfferRequests/mockOfferRequest.ts, src/booking/Offers/OfferTypes.ts
Two changes in this PR to address two issues raised by a user:
1. Added `max_connections` to `OfferRequestType`. I took the description from our docs site: https://duffel.com/docs/api/v1/offer-requests/create-offer-request#offer-requests-create-an-offer-request-body-parameters-max-connections. I also added it to our mock to prove it works correctly. (Addresses #656)
2. Use `DuffelPassengerType` instead of `'adult'` on `OfferTypes`. (Addresses #658)
=> [No Jira] Address a couple of issues

.github/workflows/release.yml
__what__
> semantic-release is written using the latest [ECMAScript 2017](https://www.ecma-international.org/publications/standards/Ecma-262.htm) features, without transpilation which requires Node version 18.0.0 or higher. ([source](https://github.com/semantic-release/semantic-release/blob/HEAD/docs/support/node-version.md#node-version-requirement))
So we need to update the version we use on CI to match. This PR fixes [this issue](https://duffel.slack.com/archives/C013XQ3T2J1/p1673519961713899).
=> fix(ci): uses node 18 for semantic-release to work

src/booking/Orders/OrdersTypes.ts
This PR adds `airline_initiated_changes` to `order`
=> feat(aics): add airline-initiated changes to orders

src/Links/Links.spec.ts, src/Links/Links.ts, src/Links/index.ts, src/index.ts
Also add a `duffel.links.generateLink` method which calls `/links/generate_link` endpoint underneath.
=> feat(links): add Links module

src/booking/AirlineInitiatedChanges/AirlineInitiatedChanges.spec.ts, src/booking/AirlineInitiatedChanges/AirlineInitiatedChanges.ts
We previously used the wrong type for the parameter. This fixes it.
=> fix(aic): fix wrong type expected in AIC update method

src/booking/OfferRequests/OfferRequests.spec.ts, src/booking/OfferRequests/OfferRequestsTypes.ts, src/booking/Offers/OfferTypes.ts, src/booking/Offers/mockOffer.ts, src/booking/Offers/mockPartialOffer.ts
This PR adds types for [private fares](https://duffel.com/docs/guides/private-fares). 
- Updated `CreateOfferRequest` interface to include `private_fares` field
- Updated `Offer` interface to include `private_fares` field
- Added `CreateOfferRequestPassengerWithFareType` interface
- Added tests for creating offer requests with private fares
- Add `CreateOfferRequestPassenger` interface with discriminated union (to enforce either `age` or `type`)
I'd recommend reviewing this PR commit-by-commit.
=> feat(booking): add private fares types

src/booking/Offers/OfferTypes.ts
Marking this optional for the time being as this type is shared with `Order` but we haven't implemented this field for `Order` just yet.
This addresses #698
=> feat(booking): add `stops` to `OfferSliceSegment`

src/Client.ts
This is so that we have more context when tackling errors (or the lack thereof).
=> feat(debug): log request id when debug mode is on

src/booking/Offers/OfferTypes.ts, src/booking/Orders/OrdersTypes.ts, src/types/shared.ts
Add tax_id to the list of identification documents that may be required for the booking.
=> feat(booking): add tax_id to PassengerIdentityDocumentType

.circleci/config.yml, .nvmrc, package.json
Node.js 14.x end of life was in April and we are updating our SDK to support Node.js 18.x as the minimum version. The reason we are not going first to 16, it's that EOL is in September.
Worth mentioning this is a breaking change for some users.
=> feat(engine): update minimum require node.js version to 18

.github/README.md, package.json
On the previous PR, we missed updating the README to reflect the new Node.js engine.
➕ Extra change:
We were [rate limited](https://github.com/duffelhq/duffel-api-javascript/actions/runs/4881478277/jobs/8710431028) on GitHub API which caused our workflow to fail, this is due to an issue with semantic-release. I've disabled comments on issues to prevent this from happening.
=> docs(readme): update README to include the minimum node.js version

src/Stays/StaysTypes.ts
This PR fixes the `confirmed_at` field type to be non-nullable.
=> fix(stays): update booking confirmed_at type to be non-nullable

src/Stays/Bookings/Bookings.ts
This PR fixes the return type of the `stays.booking.list` to be an array.
=> fix(stays): update list booking to return array

.github/renovate.json
To reduce the time we spend on maintenance.
=> build: switch to monthly dependency updates with renovate

.tool-versions, src/Stays/Bookings/Bookings.spec.ts, src/Stays/Bookings/Bookings.ts, src/Stays/StaysTypes.ts, src/Stays/mocks.ts
__what__
Based on the [upcoming API](https://www.notion.so/Loyalty-Programmes-v1-Add-To-Booking-b81abdf4bb0d43b0965002596f485a57) to allow loyalty program account numbers to be sent along with the booking code, this PR adds the types for our API client.
Bonus: [updates tools version to match the engine on package json](https://github.com/duffelhq/duffel-api-javascript/commit/53671ed01d281262d4fcbeb64f2e18544c51a358)
=> Adds loyalty types

src/Stays/StaysTypes.ts, src/Stays/mocks.ts
Add the missing type for `loyalty_programme_account_number` from https://duffel.com/docs/api/v1/bookings/schema
=> fix: add stays booking loyalty_programme_account_number

src/Stays/StaysTypes.ts, src/Stays/mocks.ts
Companion to https://github.com/duffelhq/platform/pull/15548/files, should not be merged until that is.
Pre-requisite for dashboard changes in https://duffel.atlassian.net/browse/UXP-3088 to handle different payment methods for Stays.
=> fix: add new payment_method to stays rate

src/Stays/Stays.spec.ts, src/Stays/StaysTypes.ts, src/Stays/mocks.ts
We have an upcoming release to search for accommodation.
This simply extends the types you can pass to Stays.search in the SDK to allow for accommodation based search.
This also makes sure that the SDK recognises the ID inside the accommodation as part of the main type.
An updated guide is coming out soon, but for the mean time, a preview for the new parameters is [documented in our search documentation](https://duffel.com/docs/api/v1/search/stays-search#search-search-for-accommodation-body-parameters-accommodation)
=> Accommodation based search in Duffel Javascript SDK

src/Stays/Bookings/Bookings.spec.ts, src/Stays/Bookings/Bookings.ts, src/Stays/mocks.ts
- We're about to deprecate Stays.Booking.guest.born_on from booking creation, so this is prepared once it's ready.
=> Deprecate Stays.Booking.guest.born_on

src/booking/SeatMaps/SeatMaps.spec.ts, src/booking/SeatMaps/SeatMaps.ts
Reading the [docs](https://duffel.com/docs/api/seat-maps/get-seat-maps), I'm pretty sure the return types should have been an array of seatmaps all along.
=> fix: fix seatmaps return type

src/booking/OrderChangeRequests/OrderChangeRequestsTypes.ts, src/booking/OrderChangeRequests/OrderRequestChanges.spec.ts, src/booking/OrderChangeRequests/mockOrderChangeRequests.ts
The CreateOrderChangeRequest type didn't match the latest documentation, this should fix it.
For https://duffel.atlassian.net/browse/FR-4402
=> fix: fix create order change request type

src/Stays/StaysTypes.ts
__what__
As @andrejak pointed out on [this comment](https://github.com/duffelhq/dashboard/pull/4599#discussion_r1342922984), the property could also be null. This adds the missing type.
=> fix: adds missing possible null value

src/Stays/StaysTypes.ts, src/Stays/mocks.ts
We were missing the supported loyalty programme on rates (had them on quotes and bookings, so I've pulled out the options into a type): 
https://duffel.com/docs/api/v1/search-result/fetch-all-rates#search-result-schema-accommodation-accommodation-rooms-accommodation-rooms-rates-accommodation-rooms-rates-supported-loyalty-programme
=> fix: add loyalty programme to rates

examples/with-next/package.json, examples/with-next/yarn.lock
To resolve: https://github.com/duffelhq/duffel-api-javascript/security/dependabot/16
This is a transitive dependency of Next that we use in the Next example, so I've upgraded it in there, and the example still seems to load fine.
=> build: upgrade next in the example to resovle postcss vulnerability

examples/with-next/package.json, examples/with-next/yarn.lock, src/Links/Sessions/Sessions.ts, src/Places/Suggestions/Suggestions.ts, src/booking/OfferRequests/OfferRequests.ts, src/booking/Offers/Offers.ts, src/booking/PartialOfferRequests/PartialOfferRequests.ts, src/notifications/Webhooks/Webhooks.ts
This PR changes a few Client imports that weren't using relative paths to match the rest, which will hopefully help resolve https://github.com/duffelhq/duffel-api-javascript/issues/794.
I also updated the version of the package in the example. I wasn't actually seeing this issue in the example, but I think it makes sense to keep it up to date.
=> Use relative paths for the Client more consistently

examples/with-next/components/Card.tsx, examples/with-next/package.json, examples/with-next/pages/api/book.ts, examples/with-next/pages/api/search.ts, examples/with-next/pages/index.tsx, examples/with-next/tsconfig.json, examples/with-next/yarn.lock, package.json, yarn.lock
This PR updates Typescript to 5.2.2 in both the repo and the associated example and fixes a couple associated warnings.
=> fix: update typescript version in the repo and the example

src/booking/AirlineInitiatedChanges/AirlineInitiatedChangesTypes.ts, src/booking/OfferRequests/OfferRequests.spec.ts, src/notifications/Webhooks/WebhooksType.ts
We use relative imports for `types` in most of the codebase, apart from these few instances. This PR makes that more consistent and should help with some recently seen TS issues.
=> fix: consistently use relative imports for types

package.json, src/supportingResources/Airlines/Airlines.ts
This fixes the 2nd issue mentioned in https://github.com/duffelhq/duffel-api-javascript/issues/797. 
We were getting this error, only on the Airlines class:
```
node_modules/@duffel/api/dist/typings.d.ts:3921:12 - error TS1038: A 'declare' modifier cannot be used in an already ambient context.
3921     export declare class Airlines extends Resource {
```
I tried comparing the Airlines file to other similar ones (eg Airports). Making a small change in the doc comment about Airlines helped rebuild the typings file correctly on my machine so I'm hoping/assuming that will happen on the built one too...
=> fix: fix Airlines class declaration

package.json, yarn.lock
Reverts duffelhq/duffel-api-javascript#821 - I think this is causing some problems on the dashboard (although it works fine in the simpler example projects)
=> Revert "build(deps): update dependency node-fetch to v3"

.tool-versions
__what__
Following [Norberto's lead](https://github.com/duffelhq/design-system/pull/465) and replicating this here:
> asdf no longer supports non-reproducible versions and they state that in the past that was by mistake not design. We shouldn't either.
=> use specific version for node

src/booking/Orders/OrdersTypes.ts
__what__
Looks like we were missing metadata from the CreateOrder type. We'll want to use it on duffel-components. So this PR includes it.
=> Fixes CreateOrder type

src/booking/Orders/OrdersTypes.ts
__What__
This PR exports `CreateOrderService`. This is helpful since the only other way for integrators to reference it is by replicating `Pick<OrderService, 'id' | 'quantity'>` .
=> Exports new type

src/Stays/Bookings/Bookings.ts, src/Stays/StaysTypes.ts, src/Vault/Cards/Cards.spec.ts, src/Vault/Cards/Cards.ts, src/Vault/Cards/index.ts, src/Vault/index.ts, src/index.ts
I've opened this up for review to get some feedback but some bits need a bit of tidying before actual release.
This is a prototype of how the cards tokenisation endpoint could work. Main difference is this lives on `duffel.api.cards` rather than `duffel.api.com`. 
I've put the code under Vault/Cards as the full URL is https://duffel.api.cards/vault/cards, but @igorp1 and I did discuss cleaning up that folder structure earlier today.
(I did test this worked with the next example inside the repo pointing to the local dist)
=> Add cards tokenisation endpoint

src/booking/Offers/OfferTypes.ts
__What__
Fixes types to match the [api reference](https://duffel.com/docs/api/v1/offers/schema#offers-schema-slices-slices-segments-slices-segments-arriving-at).
=> Update stop types

src/Stays/Bookings/Bookings.ts
__what__
Adds missing type for booking payload to enable paying with card id.
=> Booking payload type

src/booking/Offers/OfferTypes.ts, src/booking/Offers/mockOffer.ts, src/booking/Offers/mockPartialOffer.ts
__what__
This PR removes the `type` attribute from the metadata object.
=> fix: there's no type on the metadata object

src/Stays/StaysTypes.ts, src/Stays/mocks.ts
- This is to prepare for upcoming Rate sources
- Mergeable once API is updated with corresponding values
=> Add StaysRate.source

package.json, yarn.lock
I think this should be enough to make sure we use a set specific version of semantic-release. 
The problem was that the newer ones required Node >v20: https://duffel.slack.com/archives/C013XQ3T2J1/p1705317729095579
Local dry run:
=> fix: use a set version of semantic-release

src/booking/AirlineInitiatedChanges/mockAirlineInitiatedChanges.ts, src/booking/Offers/mockOffer.ts, src/booking/Offers/mockPartialOffer.ts, src/booking/OrderChangeOffers/mockOrderChangeOffer.ts, src/booking/OrderChangeRequests/mockOrderChangeRequests.ts, src/booking/OrderChanges/mockOrderChanges.ts, src/booking/Orders/mockOrders.ts, src/supportingResources/Airlines/AirlinesTypes.ts, src/supportingResources/Airlines/mockAirline.ts
Add missing conditions of carriage and also noticed iata_code might not be present: https://duffel.com/docs/api/airlines/schema
In the repo we're a bit inconsistent with nullable vs optional properties but let me know if you'd prefer me to keep the existing way in this file.
=> fix: update airlines types to better match schema

src/booking/OfferRequests/OfferRequests.ts, src/booking/OfferRequests/OfferRequestsTypes.ts, src/booking/PartialOfferRequests/PartialOfferRequestTypes.ts, src/booking/PartialOfferRequests/PartialOfferRequests.ts
__what__
Includes [supplier timeout](https://duffel.com/docs/api/v1/offer-requests/create-offer-request#offer-requests-create-an-offer-request-query-parameters-supplier-timeout) to offer request creation functions.
=> add supplier timeout support

src/types/shared.ts
As reported in https://github.com/duffelhq/duffel-api-javascript/issues/886 our passenger title types were not matching the documentation. This PR fixes that.
Docs here: https://duffel.com/docs/api/v1/orders/create-order#orders-create-an-order-body-parameters-passengers-passengers-title
=> fix: passenger titles

src/Stays/StaysTypes.ts, src/Stays/mocks.ts
The key collection was initially introduced to the Booking object,
but more integrations we add, it seems the best should be at Accommodation.
The key collection on Booking is deprecated, now the key collection exists in
Accommodation as preview.
=> feat: add key collection to Accommodation

rollup.config.mjs
Merging this [dependency update ](https://github.com/duffelhq/duffel-api-javascript/pull/900)caused a build failure: https://github.com/duffelhq/duffel-api-javascript/actions/runs/8685349505/job/23814635745
I think this should fix it.
=> fix: rollup/plugin-terser reference

rollup.config.mjs
Version 0.1.0 exports `default`, rather than `terser`
=> fix: Fix import for @rollup/plugin-terser

src/Client.ts
Client creates DuffelError with headers directly passed from `fetch`. Even though headers satisfy `Record<string, string>`, that type isn't usable in practice for consumers of the library, e.g. when checking rate limit headers, — `Headers` is more precise.
=> fix: specify a more precise type for DuffelError headers

src/Stays/Stays.spec.ts, src/Stays/StaysTypes.ts, src/Stays/mocks.ts
This allows some alternative occupancy parameters for future use.
=> Allow guests as payload and receive it in some responses

package.json, src/Stays/Accommodation/Accommodation.spec.ts, src/Stays/Accommodation/Accommodation.ts, src/Stays/Accommodation/index.ts, src/Stays/Stays.ts, src/Stays/StaysTypes.ts, src/Stays/mocks.ts
- This adds an `accommodation` property to the main Stays object.
- It is initialised with the suggestions function
- A new type, AccommodationSuggestions is introduced. This is an excerpt of the larger Accommodation object.
=> Allow SDK to call stays accommodation endpoint

package.json, src/Stays/Accommodation/Accommodation.spec.ts, src/Stays/Accommodation/Accommodation.ts
This adds one more accommodation fetch call. It takes a specific Duffel ID and returns a stays accommodation.
To learn more about the endpoint being called in this PR, some documentation about GET `/stays/accommodation/{id}` can be found here:
https://duffel.com/docs/api/v1/accommodation/get-accommodation
=> Implement SDK call for accommodation/{id}

.github/CODEOWNERS
Context here: https://duffel.slack.com/archives/CEA36CWLX/p1719225090881319
=> ci: remove UXP as codeowners

package.json, src/Stays/Accommodation/Accommodation.spec.ts, src/Stays/Accommodation/Accommodation.ts, src/Stays/StaysTypes.ts
This patches the current suggestions SDK kit to be able to receive an optional location. 
It will restrict suggestions only to said location when supplied.
=> Add optional location parameter to suggestions SDK

package.json, src/Stays/LoyaltyProgrammes/LoyaltyProgrammes.spec.ts, src/Stays/LoyaltyProgrammes/LoyaltyProgrammes.ts, src/Stays/LoyaltyProgrammes/index.ts, src/Stays/Stays.ts, src/Stays/StaysTypes.ts, src/Stays/mocks.ts
This adds the Loyalty Programmes resource to the SDK. This allows fetching of information about the loyalty programmes supported by Accommodation or Rates. 
To learn more about the endpoint being called in this PR, the Stays loyalty programme documentation can be found [here](https://duffel.com/docs/api/v1/accommodation-loyalty-programmes).
=> feat: add stays loyalty programmes resource

package.json, src/Stays/StaysTypes.ts, src/Stays/mocks.ts
There are now new smaller png logos for different use case on loyalty programme. So we now read it from the API once it gets updated.
=> Read more logo urls from updated api

package.json, src/Stays/StaysTypes.ts, src/Stays/mocks.ts
since logo_url is just a duplicate of logo_url_svg and no one is using it, we remove it from the SDK
=> Remove deprecated logo_url

package.json, src/Stays/StaysTypes.ts, src/Stays/mocks.ts
We introduced a change to our responses, such that it should reflect the given email and phone number for the booking. This should streamline some important information for integrators much better.
=> Read booking contacts from API response

src/booking/Identity/ComponentClientKey/ComponentClientKeys.spec.ts, src/booking/Identity/ComponentClientKey/ComponentClientKeys.ts, src/booking/Identity/ComponentClientKey/mockComponentClientKey.ts, src/booking/Identity/ComponentClientKey/types.ts
__what__
We are soon to make component client keys public in our API reference. To better support or merchants in using that endpoint, this PR adds component client key creation to our client.
=> Introduces component client keys

src/Stays/Bookings/Bookings.ts
This adds ability to allow 3ds payments for bookings.
=> feat: allow 3ds session ID for payments on bookings

package.json, src/booking/OfferRequests/OfferRequestsTypes.ts, src/booking/OfferRequests/mockOfferRequest.ts, src/booking/Orders/OrdersTypes.ts, src/booking/PartialOfferRequests/mockPartialOfferRequest.ts
Fixes issues reported in https://github.com/duffelhq/duffel-api-javascript/issues/936 ([guide](https://duffel.com/docs/guides/following-search-best-practices)) and https://github.com/duffelhq/duffel-api-javascript/issues/945.
=> Fix more types

package.json
Version bump in package.json and package-lock.json for release 3.1.2
Attempting to do this manually since something seems to be broken with the automation (duffel-bot is not creating the PRs). Will look into that next.
=> ci(release): 3.1.2

docs/CONTRIBUTING.md
My current theory about why automatic release has been failing recently is because we've defaulted to Squash commits, which alter the commit message, so it doesn't hit the right triggers. More discussion here: https://github.com/semantic-release/commit-analyzer/issues/177
This is basically a test commit where I'll try a normal merge and see if the release is triggered.
=> fix: testing if squash merging is the problem

package.json, src/Stays/Brands/Brands.spec.ts, src/Stays/Brands/Brands.ts, src/Stays/Brands/index.ts, src/Stays/Stays.ts, src/Stays/StaysTypes.ts, src/Stays/mocks.ts
We are preparing to expose brands endpoints as types and calls via our SDK.
This also cleans up the mock accommodation to have an accurate representation of brand and chain from actual duffel data.
- https://duffel.com/docs/api/v2/brands
=> Expose brands to JS SDK

src/Stays/Bookings/Bookings.spec.ts, src/Stays/Bookings/Bookings.ts
The https://duffel.com/docs/api/bookings/list-bookings now supports pagination params.
So it mimics add pagination parameters like it does for Flights orders.
=> feat: add pagination params support to list Stays Bookings

src/booking/SeatMaps/SeatMapTypes.ts
We received a [report that seat maps looked broken](https://duffel.atlassian.net/browse/FR-8249?focusedCommentId=43085). That's because the component encountered an element type it was not equipped to handle, this PR adds the element type to our typescript definition, so we can use it to update the component.
=> Adds missing type to seat map element

src/Stays/StaysTypes.ts
The `region` field on `StaysAddress` is marked as a `string`, but at run time we have received `null`.
I am unsure if the fix should instead be ensuring `region` is never null, but if wanted, this PR updates the type to a nullable string.
=> Fix: `StaysAddress` `region` type

src/Stays/Bookings/Bookings.spec.ts, src/Stays/Bookings/Bookings.ts
This allows metadata to be passed as payload when creating stays bookings via the js sdk
=> feat: allow metadata in booking creation payload

src/booking/Offers/OfferTypes.ts, src/booking/Offers/mockOffer.ts, src/booking/Offers/mockPartialOffer.ts, src/booking/Orders/OrdersTypes.ts, src/booking/Orders/mockOrders.ts
We were missing the [slice comparison key](https://duffel.com/docs/api/v2/offers#offers-schema-slices-slices-comparison-key) and [order cancellations](https://duffel.com/docs/api/v2/orders#orders-schema-cancellation).
=> fix: add missing types

src/Stays/Quotes/Quotes.spec.ts, src/Stays/Quotes/Quotes.ts
The GET quote endpoint is missing from our client library. This PR corrects that.
=> Adds get quote operation for stays

src/functions/hasAvailableSeatService.spec.ts, src/functions/hasAvailableSeatService.ts, src/functions/hasService.spec.ts, src/functions/hasService.ts, src/index.ts
__what__
Adds new functions to help merchants determine if services are present on an offer or seat map.
=> Exposes `hasService` helper

src/booking/OrderChanges/OrderChangesTypes.ts
=> fix: order change type

src/Stays/Bookings/Bookings.spec.ts, src/Stays/Bookings/Bookings.ts, src/Stays/mocks.ts, src/booking/Orders/OrdersTypes.ts, src/booking/Orders/mockOrders.ts
So our users can rely on our types instead of needing to make type assertions
=> Adds user related types to order and booking creation

src/Stays/StaysTypes.ts, src/Stays/mocks.ts
Adds the following new fields to the Stays types based on recent releases.
- review count on Accommodation type
- deposit amount and currency on Quote type
- cheapest rate base and due_at_accommodation details on SearchResult type
=> feat: add new fields to Stays types [STAY-3590]

src/booking/AirlineInitiatedChanges/mockAirlineInitiatedChanges.ts, src/booking/Orders/OrdersTypes.ts, src/booking/Orders/mockOrders.ts
Adds missing fare_brand_name in order slice
=> chore: adds missing type
